import type { ArmyState } from "../army/types";
import { normalizeArmyDivisions } from "../army/divisions";
import { defaultStaffAssignments } from "../army/headquarters";
import type { Officer } from "../officers/types";
import { createInitialResources } from "../logistics/types";
import { createTheater } from "../theater/createTheater";
import { applyStrategicTurnToTheater, generateStrategicTurn } from "../theater/generateStrategicTurn";
import type { CampaignState } from "./types";
import { assertScenarioPackValid, borderEmergencyScenarioPack } from "../../content/registries";

const initialOfficers = (): Officer[] => [
  {
    id: "officer-voss",
    name: "フォス",
    rank: "Major",
    experience: 34,
    status: "active",
    recoveryTurns: 0,
    commandFatigue: 0,
    traits: ["規律重視"],
    assignedUnitId: "unit-infantry-1",
    history: ["第1大隊に配属"],
  },
  {
    id: "officer-keller",
    name: "ケラー",
    rank: "Captain",
    experience: 18,
    status: "active",
    recoveryTurns: 0,
    commandFatigue: 0,
    traits: ["散兵指揮"],
    assignedUnitId: "unit-jaeger-1",
    history: ["国境哨戒の古参"],
  },
  {
    id: "officer-arnheim",
    name: "アルンハイム",
    rank: "Colonel",
    experience: 46,
    status: "active",
    recoveryTurns: 0,
    commandFatigue: 0,
    traits: ["砲兵運用"],
    assignedUnitId: "unit-artillery-1",
    history: ["鉄道集積地防衛計画を担当"],
  },
  {
    id: "officer-metz",
    name: "メッツ",
    rank: "Captain",
    experience: 21,
    status: "active",
    recoveryTurns: 0,
    commandFatigue: 0,
    traits: ["工兵指揮"],
    assignedUnitId: "unit-engineer-1",
    history: ["東方辺境の胸壁構築を指揮"],
  },
  {
    id: "officer-kruger",
    name: "クルーガー",
    rank: "Major",
    experience: 29,
    status: "active",
    recoveryTurns: 0,
    commandFatigue: 0,
    traits: ["戦列保持"],
    assignedUnitId: "unit-infantry-2",
    history: ["予備戦列を再編"],
  },
  {
    id: "officer-stein",
    name: "シュタイン",
    rank: "Captain",
    experience: 22,
    status: "active",
    recoveryTurns: 0,
    commandFatigue: 0,
    traits: ["塹壕戦"],
    assignedUnitId: "unit-infantry-3",
    history: ["湿地前面で後退戦を経験"],
  },
  {
    id: "officer-bauer",
    name: "バウアー",
    rank: "Captain",
    experience: 19,
    status: "active",
    recoveryTurns: 0,
    commandFatigue: 0,
    traits: ["火力支援"],
    assignedUnitId: "unit-artillery-2",
    history: ["橋梁砲兵陣地を担当"],
  },
  {
    id: "officer-hartmann",
    name: "ハルトマン",
    rank: "Captain",
    experience: 16,
    status: "active",
    recoveryTurns: 0,
    commandFatigue: 0,
    traits: ["哨戒"],
    assignedUnitId: "unit-jaeger-2",
    history: ["北森の偵察線を維持"],
  },
  {
    id: "officer-weber",
    name: "ヴェーバー",
    rank: "Major",
    experience: 25,
    status: "active",
    recoveryTurns: 0,
    commandFatigue: 0,
    traits: ["予備指揮"],
    assignedUnitId: "unit-infantry-4",
    history: ["本国予備兵を前線へ移送"],
  },
  {
    id: "officer-lenz",
    name: "レンツ",
    rank: "Captain",
    experience: 14,
    status: "active",
    recoveryTurns: 0,
    commandFatigue: 0,
    traits: ["野戦架橋"],
    assignedUnitId: "unit-engineer-2",
    history: ["補給路の応急修理を担当"],
  },
];

const initialArmy = (): ArmyState => ({
  formations: [
    {
      id: "formation-eastmark",
      name: "東方辺境第I軍団",
      unitIds: [
        "unit-infantry-1",
        "unit-infantry-2",
        "unit-jaeger-1",
        "unit-artillery-1",
        "unit-infantry-3",
        "unit-engineer-1",
        "unit-infantry-4",
        "unit-jaeger-2",
        "unit-artillery-2",
        "unit-engineer-2",
      ],
      divisions: normalizeArmyDivisions([], [
        {
          id: "division-1",
          name: "第1師団",
          note: "主戦列",
          role: "line",
          directive: "line_hold",
          commanderOfficerId: "officer-voss",
          maxBrigades: 6,
          unitIds: [
            "unit-infantry-1",
            "unit-infantry-2",
            "unit-jaeger-1",
            "unit-artillery-1",
            "unit-infantry-3",
            "unit-engineer-1",
          ],
        },
        {
          id: "division-2",
          name: "第2師団",
          note: "予備・支援",
          role: "reserve",
          directive: "reserve_guard",
          commanderOfficerId: "officer-weber",
          maxBrigades: 6,
          unitIds: ["unit-infantry-4", "unit-jaeger-2", "unit-artillery-2", "unit-engineer-2"],
        },
        {
          id: "division-3",
          name: "第3師団",
          note: "軍制拡張で解放",
          role: "locked",
          directive: "line_hold",
          maxBrigades: 6,
          unitIds: [],
          locked: true,
        },
        {
          id: "division-4",
          name: "第4師団",
          note: "軍制拡張で解放",
          role: "locked",
          directive: "line_hold",
          maxBrigades: 6,
          unitIds: [],
          locked: true,
        },
      ]),
      staffAssignments: defaultStaffAssignments().map((assignment) => {
        if (assignment.slotId === "chiefOfStaff") {
          return { ...assignment, officerId: "officer-arnheim" };
        }
        if (assignment.slotId === "quartermaster") {
          return { ...assignment, officerId: "officer-weber" };
        }
        if (assignment.slotId === "engineerChief") {
          return { ...assignment, officerId: "officer-metz" };
        }
        if (assignment.slotId === "artilleryChief") {
          return { ...assignment, officerId: "officer-bauer" };
        }
        return assignment;
      }),
    },
  ],
  units: [
    {
      id: "unit-infantry-1",
      name: "第1戦列歩兵大隊",
      type: "infantry",
      soldiers: 760,
      maxSoldiers: 820,
      experience: 36,
      level: 1,
      morale: 78,
      condition: 86,
      ammo: 92,
      weaponQuality: 1,
      officerId: "officer-voss",
      traits: ["堅実"],
      battleHistory: ["鉄道前面を保持"],
    },
    {
      id: "unit-infantry-2",
      name: "第4戦列歩兵大隊",
      type: "infantry",
      soldiers: 690,
      maxSoldiers: 760,
      experience: 30,
      level: 1,
      morale: 72,
      condition: 84,
      ammo: 88,
      weaponQuality: 0.96,
      officerId: "officer-kruger",
      traits: ["戦列保持"],
      battleHistory: ["予備線から前進"],
    },
    {
      id: "unit-jaeger-1",
      name: "東方辺境猟兵隊",
      type: "jaeger",
      soldiers: 280,
      maxSoldiers: 320,
      experience: 42,
      level: 1,
      morale: 74,
      condition: 90,
      ammo: 86,
      weaponQuality: 1.12,
      officerId: "officer-keller",
      traits: ["森林戦"],
      battleHistory: ["黒沼を偵察"],
    },
    {
      id: "unit-artillery-1",
      name: "第3野戦砲兵中隊",
      type: "artillery",
      soldiers: 132,
      maxSoldiers: 150,
      experience: 31,
      level: 1,
      morale: 68,
      condition: 82,
      ammo: 78,
      weaponQuality: 1.28,
      officerId: "officer-arnheim",
      traits: ["対砲兵"],
      battleHistory: ["前線補給所を援護"],
    },
    {
      id: "unit-infantry-3",
      name: "第6塹壕歩兵大隊",
      type: "infantry",
      soldiers: 640,
      maxSoldiers: 720,
      experience: 24,
      level: 1,
      morale: 69,
      condition: 80,
      ammo: 82,
      weaponQuality: 0.92,
      officerId: "officer-stein",
      traits: ["塹壕戦"],
      battleHistory: ["湿地掩体を保持"],
    },
    {
      id: "unit-engineer-1",
      name: "第2工兵中隊",
      type: "engineer",
      soldiers: 210,
      maxSoldiers: 240,
      experience: 28,
      level: 1,
      morale: 72,
      condition: 88,
      ammo: 62,
      weaponQuality: 0.8,
      officerId: "officer-metz",
      traits: ["野戦築城"],
      battleHistory: ["東方辺境防衛線を補強"],
    },
    {
      id: "unit-infantry-4",
      name: "衛戍予備歩兵大隊",
      type: "infantry",
      soldiers: 580,
      maxSoldiers: 700,
      experience: 18,
      level: 1,
      morale: 64,
      condition: 78,
      ammo: 76,
      weaponKey: "reserveRifle",
      weaponQuality: 0.88,
      officerId: "officer-weber",
      traits: ["予備兵"],
      battleHistory: ["本国中枢から転用"],
    },
    {
      id: "unit-jaeger-2",
      name: "北森猟兵分隊",
      type: "jaeger",
      soldiers: 210,
      maxSoldiers: 260,
      experience: 27,
      level: 1,
      morale: 70,
      condition: 86,
      ammo: 82,
      weaponQuality: 1.04,
      officerId: "officer-hartmann",
      traits: ["哨戒"],
      battleHistory: ["北森の視界線を確保"],
    },
    {
      id: "unit-artillery-2",
      name: "第1重砲分遣隊",
      type: "artillery",
      soldiers: 96,
      maxSoldiers: 120,
      experience: 22,
      level: 1,
      morale: 63,
      condition: 76,
      ammo: 72,
      weaponQuality: 1.18,
      officerId: "officer-bauer",
      traits: ["榴弾砲"],
      battleHistory: ["橋梁正面を砲撃"],
    },
    {
      id: "unit-engineer-2",
      name: "第3架橋工兵分遣隊",
      type: "engineer",
      soldiers: 150,
      maxSoldiers: 190,
      experience: 20,
      level: 1,
      morale: 66,
      condition: 82,
      ammo: 58,
      weaponQuality: 0.76,
      officerId: "officer-lenz",
      traits: ["架橋"],
      battleHistory: ["補給道を応急復旧"],
    },
  ],
});

export const createCampaign = (): CampaignState => {
  assertScenarioPackValid(borderEmergencyScenarioPack);
  const theater = createTheater();
  const activeStrategicTurn = generateStrategicTurn(theater);
  const theaterWithTurn = applyStrategicTurnToTheater(theater, activeStrategicTurn);

  return {
    id: `campaign-${Date.now()}`,
    turnNumber: 1,
    resources: createInitialResources(),
    army: initialArmy(),
    officers: initialOfficers(),
    theater: theaterWithTurn,
    doctrines: { unlocked: ["command"], points: 1, staffIntelligenceDirective: "balanced" },
    standingOrderTemplates: [],
    standingOrderPlanSets: [],
    deploymentPlan: undefined,
    battleHistory: [],
    activeStrategicTurn,
    saveVersion: 8,
    lastMessage: "東方辺境防衛線で戦役が始まった。",
  };
};
