import type { FortificationInstance } from "../fortifications/types";
import type { Sector, TheaterState } from "./types";

const startingTrench: FortificationInstance = {
  id: "fort-active-front-trench-1",
  type: "trench",
  sectorId: "active-front-eastmark",
  mapNodeId: "eastmark-main-line",
  durability: 86,
  maxDurability: 100,
  level: 1,
  status: "built",
  history: ["開戦前に構築された主塹壕線"],
};

const startingDepot: FortificationInstance = {
  id: "fort-forward-depot-1",
  type: "supplyDepot",
  sectorId: "forward-belt-railhead",
  mapNodeId: "railhead-depot",
  durability: 78,
  maxDurability: 85,
  level: 1,
  status: "built",
  history: ["前線補給所を設置済み"],
};

export const createInitialSectors = (): Sector[] => [
  {
    id: "home-core-citadel",
    name: "クローネ要塞前面",
    band: "homeCoreDefense",
    control: "player",
    terrainTags: ["village", "hill"],
    fortificationSlots: 5,
    structures: [],
    supplyValue: 18,
    railValue: 14,
    medicalValue: 12,
    engineerValue: 10,
    enemyPressure: 8,
    corruptionLevel: 0,
    battleTemplates: ["line-defense"],
    linkedSectors: ["forward-belt-railhead"],
    history: ["本国中枢の予備防衛線"],
  },
  {
    id: "forward-belt-railhead",
    name: "アイゼンブルック鉄道集積地",
    band: "forwardDefense",
    control: "player",
    terrainTags: ["bridge", "village", "trench"],
    fortificationSlots: 4,
    structures: [startingDepot],
    supplyValue: 16,
    railValue: 18,
    medicalValue: 8,
    engineerValue: 9,
    enemyPressure: 24,
    corruptionLevel: 6,
    battleTemplates: ["bridge-hold", "line-defense"],
    linkedSectors: ["home-core-citadel", "active-front-eastmark"],
    history: ["前線補給の要衝"],
  },
  {
    id: "active-front-eastmark",
    name: "東方辺境防衛線",
    band: "activeFront",
    control: "contested",
    terrainTags: ["forest", "marsh", "trench"],
    fortificationSlots: 3,
    structures: [startingTrench],
    supplyValue: 10,
    railValue: 5,
    medicalValue: 5,
    engineerValue: 7,
    enemyPressure: 42,
    corruptionLevel: 24,
    battleTemplates: ["line-defense", "village-delay"],
    linkedSectors: ["forward-belt-railhead", "enemy-vanguard-nest"],
    history: ["現在の主力軍位置"],
  },
  {
    id: "enemy-vanguard-nest",
    name: "黒沼の敵前進巣",
    band: "enemyVanguard",
    control: "enemy",
    terrainTags: ["marsh", "forest"],
    fortificationSlots: 1,
    structures: [],
    supplyValue: 4,
    railValue: 0,
    medicalValue: 0,
    engineerValue: 2,
    enemyPressure: 66,
    corruptionLevel: 58,
    battleTemplates: ["village-delay"],
    linkedSectors: ["active-front-eastmark", "enemy-heartland-ossuary"],
    history: ["アンデッド前衛集結地"],
  },
  {
    id: "enemy-heartland-ossuary",
    name: "納骨荒野",
    band: "enemyHeartland",
    control: "enemy",
    terrainTags: ["open", "marsh"],
    fortificationSlots: 0,
    structures: [],
    supplyValue: 0,
    railValue: 0,
    medicalValue: 0,
    engineerValue: 0,
    enemyPressure: 88,
    corruptionLevel: 80,
    battleTemplates: ["line-defense"],
    linkedSectors: ["enemy-vanguard-nest"],
    history: ["敵本国側の戦略縦深"],
  },
];

export const createTheater = (): TheaterState => ({
  currentFrontBand: "activeFront",
  playerArmyPositionSectorId: "active-front-eastmark",
  rearPressureSectorIds: ["forward-belt-railhead"],
  forwardPressureSectorIds: ["enemy-vanguard-nest"],
  sectors: createInitialSectors(),
  globalThreat: 42,
  enemyMomentum: 8,
  playerStrategicInitiative: 4,
  campaignChapter: "国境非常態勢",
  turnNumber: 1,
  activeOperations: [],
  mandatoryBattle: undefined,
  strategicHistory: ["東方辺境防衛線に敵圧が集中している。"],
});
