import { createScenarioPackTemplate } from "../templates/scenarioPackTemplate";

export const borderEmergencyScenarioPack = createScenarioPackTemplate({
  id: "border-emergency-001",
  name: "国境非常態勢",
  chapter: "第1章 / 東方辺境防衛線",
  strategic: {
    currentSectorId: "active-front-eastmark",
    rearPressureSectorIds: ["forward-belt-railhead"],
    forwardPressureSectorIds: ["enemy-vanguard-nest"],
    globalThreat: 42,
    enemyMomentum: 8,
    playerStrategicInitiative: 4,
    sectors: [
      {
        id: "home-core-citadel",
        name: "クローネ要塞前面",
        band: "homeCoreDefense",
        control: "player",
        terrainTags: ["village", "hill"],
        fortificationSlots: 5,
        supplyValue: 18,
        railValue: 14,
        medicalValue: 12,
        engineerValue: 10,
        enemyPressure: 8,
        corruptionLevel: 0,
        battleTemplates: ["line-defense"],
        linkedSectors: ["forward-belt-railhead"],
        history: ["本国中枢の予備防衛線"],
      },
      {
        id: "forward-belt-railhead",
        name: "アイゼンブルック鉄道集積地",
        band: "forwardDefense",
        control: "player",
        terrainTags: ["bridge", "village", "trench"],
        fortificationSlots: 4,
        initialStructures: [
          {
            id: "fort-forward-depot-1",
            type: "supplyDepot",
            sectorId: "forward-belt-railhead",
            mapNodeId: "railhead-depot",
            durability: 78,
            maxDurability: 85,
            level: 1,
            status: "built",
            history: ["前線補給所を設置済み"],
          },
        ],
        supplyValue: 16,
        railValue: 18,
        medicalValue: 8,
        engineerValue: 9,
        enemyPressure: 24,
        corruptionLevel: 6,
        battleTemplates: ["bridge-hold", "line-defense"],
        linkedSectors: ["home-core-citadel", "active-front-eastmark"],
        history: ["前線補給の要衝"],
      },
      {
        id: "active-front-eastmark",
        name: "東方辺境防衛線",
        band: "activeFront",
        control: "contested",
        terrainTags: ["forest", "marsh", "trench"],
        fortificationSlots: 3,
        initialStructures: [
          {
            id: "fort-active-front-trench-1",
            type: "trench",
            sectorId: "active-front-eastmark",
            mapNodeId: "eastmark-main-line",
            durability: 86,
            maxDurability: 100,
            level: 1,
            status: "built",
            history: ["開戦前に構築された主塹壕線"],
          },
        ],
        supplyValue: 10,
        railValue: 5,
        medicalValue: 5,
        engineerValue: 7,
        enemyPressure: 42,
        corruptionLevel: 24,
        battleTemplates: ["line-defense", "village-delay"],
        linkedSectors: ["forward-belt-railhead", "enemy-vanguard-nest"],
        history: ["現在の主力軍位置"],
      },
      {
        id: "enemy-vanguard-nest",
        name: "黒沼の敵前進巣",
        band: "enemyVanguard",
        control: "enemy",
        terrainTags: ["marsh", "forest"],
        fortificationSlots: 1,
        supplyValue: 4,
        railValue: 0,
        medicalValue: 0,
        engineerValue: 2,
        enemyPressure: 66,
        corruptionLevel: 58,
        battleTemplates: ["village-delay"],
        linkedSectors: ["active-front-eastmark", "enemy-heartland-ossuary"],
        history: ["アンデッド前衛集結地"],
      },
      {
        id: "enemy-heartland-ossuary",
        name: "納骨荒野",
        band: "enemyHeartland",
        control: "enemy",
        terrainTags: ["open", "marsh"],
        fortificationSlots: 0,
        supplyValue: 0,
        railValue: 0,
        medicalValue: 0,
        engineerValue: 0,
        enemyPressure: 88,
        corruptionLevel: 80,
        battleTemplates: ["line-defense"],
        linkedSectors: ["enemy-vanguard-nest"],
        history: ["敵本国側の戦略縦深"],
      },
    ],
  },
  tactical: {
    battleTemplateIds: ["line-defense", "bridge-hold", "village-delay"],
    mainBattleTemplateId: "line-defense",
    description: "戦略mapの主戦場を省略せず、半自律戦術と戦果持越しを検証する第1シナリオ。",
  },
  operations: {
    mandatoryBattle: {
      id: "main-hold-sector",
      titleTemplate: "{currentSector.name}防衛戦",
      type: "holdSector",
      sectorId: "active-front-eastmark",
      isMandatory: true,
      canAutoResolve: false,
      risk: 0.42,
      cost: {},
      victoryEffects: { enemyPressureDelta: -6, reputationDelta: 1 },
      drawEffects: { enemyPressureDelta: -3, waveBudgetDelta: -4 },
      defeatEffects: { enemyPressureDelta: 6, enemyMomentumDelta: 1, reputationDelta: -1 },
    },
    sideOperations: [
      {
        id: "recon-forward-nest",
        titleTemplate: "{forwardSector.name}偵察",
        type: "reconPatrol",
        sectorId: "enemy-vanguard-nest",
        isMandatory: false,
        canAutoResolve: true,
        risk: 0.22,
        cost: {},
        victoryEffects: { waveBudgetDelta: -8, initiativeDelta: 2 },
        drawEffects: { enemyPressureDelta: -3, waveBudgetDelta: -4 },
        defeatEffects: { enemyPressureDelta: 6, enemyMomentumDelta: 1, reputationDelta: -1 },
      },
      {
        id: "raid-forward-nest",
        titleTemplate: "{forwardSector.name}襲撃",
        type: "raidEnemyNest",
        sectorId: "enemy-vanguard-nest",
        isMandatory: false,
        canAutoResolve: true,
        risk: 0.48,
        cost: { ammunition: 40, supplies: 12 },
        victoryEffects: { enemyPressureDelta: -12, enemyMomentumDelta: -2, waveBudgetDelta: -18, reputationDelta: 2 },
        drawEffects: { enemyPressureDelta: -3, waveBudgetDelta: -4 },
        defeatEffects: { enemyPressureDelta: 6, enemyMomentumDelta: 1, reputationDelta: -1 },
      },
      {
        id: "engineer-active-front",
        titleTemplate: "{currentSector.name}増強工事",
        type: "engineerWorks",
        sectorId: "active-front-eastmark",
        isMandatory: false,
        canAutoResolve: true,
        risk: 0.18,
        cost: { materials: 25, engineerLabor: 12 },
        victoryEffects: { structureRepair: 22, initiativeDelta: 1 },
        drawEffects: { enemyPressureDelta: -3, waveBudgetDelta: -4 },
        defeatEffects: { enemyPressureDelta: 6, enemyMomentumDelta: 1, reputationDelta: -1 },
      },
      {
        id: "rail-repair-forward-belt",
        titleTemplate: "{rearSector.name}復旧",
        type: "railRepair",
        sectorId: "forward-belt-railhead",
        isMandatory: false,
        canAutoResolve: true,
        risk: 0.28,
        cost: { materials: 22, engineerLabor: 8 },
        victoryEffects: { resourceDelta: { supplies: 30, ammunition: 35 }, initiativeDelta: 1 },
        drawEffects: { enemyPressureDelta: -3, waveBudgetDelta: -4 },
        defeatEffects: { enemyPressureDelta: 6, enemyMomentumDelta: 1, reputationDelta: -1 },
      },
    ],
  },
  carryover: {
    visibleResultFields: ["enemyPressure", "enemyMomentum", "resources", "battleHistory", "tacticalLessons"],
    requiredBattlePersistence: true,
    nextTurnSummaryFields: ["battleHistory", "enemyPressure", "resources", "tacticalLessons"],
  },
});

export const scenarioPacks = [borderEmergencyScenarioPack] as const;
