export const weaponDefinitions = {
  reserveRifle: {
    name: "後装旧式銃",
    quality: 0.86,
    range: 25,
    firepower: 0.82,
    fireRate: 0.92,
    compatibleTypes: ["infantry"] as const,
    assetKey: "dreyse",
    role: "予備戦列",
  },
  dreyse: {
    name: "針撃銃",
    quality: 1.0,
    range: 30,
    firepower: 1.0,
    fireRate: 1.0,
    compatibleTypes: ["infantry"] as const,
    assetKey: "dreyse",
    role: "標準戦列",
  },
  mauser71: {
    name: "改良針撃銃",
    quality: 1.16,
    range: 36,
    firepower: 1.12,
    fireRate: 0.9,
    compatibleTypes: ["infantry"] as const,
    assetKey: "dreyse",
    role: "精鋭戦列",
  },
  jaegerRifle: {
    name: "猟兵銃",
    quality: 1.12,
    range: 42,
    firepower: 0.9,
    fireRate: 0.85,
    compatibleTypes: ["jaeger"] as const,
    assetKey: "jaegerRifle",
    role: "散兵/森林",
  },
  fieldGun: {
    name: "野戦砲",
    quality: 1.28,
    range: 64,
    firepower: 2.8,
    fireRate: 0.48,
    compatibleTypes: ["artillery"] as const,
    assetKey: "fieldGun",
    role: "火力支援",
  },
  tools: {
    name: "工兵器材",
    quality: 0.8,
    range: 16,
    firepower: 0.45,
    fireRate: 0.65,
    compatibleTypes: ["engineer"] as const,
    assetKey: "tools",
    role: "築城/修理",
  },
} as const;
